# Generated by Django 3.1.7 on 2021-03-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricetype', '0002_auto_20210313_1042'),
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pricetype',
            field=models.ManyToManyField(blank=True, related_name='catpricetype', to='pricetype.Pricetype'),
        ),
    ]
