# Generated by Django 3.1.7 on 2021-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.BooleanField(blank=True, default=False)),
                ('bid', models.BooleanField(blank=True, default=False)),
                ('bidoptional', models.BooleanField(blank=True, default=False)),
                ('payment', models.BooleanField(blank=True, default=False)),
                ('buybutton', models.BooleanField(blank=True, default=False)),
                ('buybuttontxt', models.TextField(blank=True, null=True)),
                ('pricetag', models.BooleanField(blank=True, default=False)),
                ('pricetagtxt', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
