# Generated by Django 3.1.7 on 2021-03-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricetype', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetype',
            name='id',
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
