# Generated by Django 3.1.7 on 2021-03-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_emailpay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='emailnoti',
            new_name='msgnoti',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='emailpay',
            new_name='paynoti',
        ),
    ]
