# Generated by Django 3.1.7 on 2021-03-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
    ]
