# Generated by Django 3.1.7 on 2021-03-13 09:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pricetype', '0002_auto_20210313_1042'),
        ('categorys', '0002_category_pricetype'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='listing',
            name='buybutton',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='buybuttontxt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categorys.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='pricetag',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='pricetagtxt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pricetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricetype', to='pricetype.pricetype'),
        ),
    ]
