# Generated by Django 3.1.7 on 2021-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricetype', '0002_auto_20210313_1042'),
        ('listings', '0002_auto_20210313_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='pricetype',
        ),
        migrations.AddField(
            model_name='listing',
            name='pricetype',
            field=models.ManyToManyField(blank=True, related_name='listpricetype', to='pricetype.Pricetype'),
        ),
    ]
