# Generated by Django 3.1.7 on 2021-03-13 10:56

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pricetype', '0002_auto_20210313_1042'),
        ('listings', '0004_auto_20210313_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pricetype',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricetype.pricetype'),
        ),
    ]
