# Generated by Django 3.1.7 on 2021-03-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210313_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='firstimage',
        ),
    ]
