# Generated by Django 3.1.7 on 2021-03-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricetype', '0002_auto_20210313_1042'),
        ('listings', '0006_auto_20210314_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pricetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricetype.pricetype'),
        ),
    ]
