# Generated by Django 3.1.7 on 2021-03-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210314_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='buybutton',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='buybuttontxt',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='deliverycost',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='pricetag',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='pricetagtxt',
        ),
    ]
