# Generated by Django 3.1.7 on 2021-03-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210319_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='firstimage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='pricetype',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='secondimage',
        ),
    ]
