# Generated by Django 3.1.7 on 2021-03-20 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20210320_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
    ]
