# Generated by Django 3.1.7 on 2021-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='firstimage',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
