# Generated by Django 3.1.7 on 2021-03-22 07:00

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pricetype', '0002_auto_20210313_1042'),
        ('categorys', '0002_category_pricetype'),
        ('listings', '0011_listing_firstimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categorys.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='deliverycost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='pickup',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pricetext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pricetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricetype.pricetype'),
        ),
        migrations.AddField(
            model_name='listing',
            name='secondimage',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
