# Generated by Django 3.1.7 on 2021-03-24 18:54

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20210324_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]+$', 'Only numbers, spaces and alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]+$', 'Only numbers, spaces and alphanumeric characters are allowed.')]),
        ),
    ]
