# Generated by Django 3.1.7 on 2021-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20210404_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='buybuttontxt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
