# Generated by Django 3.2.4 on 2021-06-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_buybuttontxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidoptional',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
