# Generated by Django 3.2.4 on 2021-06-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_listing_bidoptional'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='secondthumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='firstimage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='secondimage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
