# Generated by Django 3.2.4 on 2021-06-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20210627_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='secondthumbnail',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='thumbnail',
        ),
    ]
